### ISSUE TITLE
docker and keynav like

### ISSUE THREAD

**Issue by vincentaxhe** [hyprland-community/awesome-hyprland#110]
deadd notification center is good, I recommend it.
can not find useful docker running with hyprland yet,[ lavalauncher is not available](https://github.com/hyprwm/Hyprland/issues/6913).
[waypoint](https://github.com/tadeokondrak/waypoint) is the only keynav replacement?

**Comment by yavko** [comment]
I'm not sure what you're asking for, do you want dead notification center, waypoint, and lavalauncher added?

**Comment by vincentaxhe** [comment]
> I'm not sure what you're asking for, do you want dead notification center, waypoint, and lavalauncher added?

I want deadd notification add beside mako, it support css, is really great. and make new categories as 'dock' and 'keynav replacement' which are pain spots.

**Comment by yavko** [comment]
Still confused what you mean, i wont add deadd as even if it does support wayland, which iirc it doesnt, its outdated.
