### ISSUE TITLE
Pyprland isn't listed in plugins !!!

### ISSUE THREAD

**Issue by fdev31** [hyprland-community/awesome-hyprland#32]
And that's really a shame ;)

**Comment by yavko** [comment]
Yeah cuz the section is for c++ plugins that you load into the compositor. Idk what to put pyprland under

**Comment by fdev31** [comment]
I see now there are no exceptions indeed...

Maybe something like "Official plugins" but called "external plugins" or "IPC plugins" or something like that ?
I *guess* there are more tools doing something close... ?
Else just with the label "Py" instead of "c++" it would be quite explicit (in the plugins section)
At least to me it still fits in some kind of "plugin" section, it's like addons for Hyprland... it just happens that there are two types, the "loaded" ones and the "remote" ones...

**Comment by fdev31** [comment]
thank you :)
