### ISSUE TITLE
Virtual keyboard

### ISSUE THREAD

**Issue by JeanSchoeller** [hyprland-community/awesome-hyprland#5]
After playing around with a lot virtual keyboards, I think that wvkbd (https://github.com/jjsullivan5196/wvkbd) qualifies as the most useful virtual keyboard right now for Hyprland. (can also be implemented in greetd for login without keyboards for tablet users)
Might want to add to the list.

**Comment by yavko** [comment]
Looks cool, I'll add it once I get on my computer

**Comment by yavko** [comment]
Done
